---
title: "Untitled"
output: html_document
---

```{r}
library(ggplot2)
library(plyr)

rm(list=ls())
d <- read.csv("~/Projects/cookie_choice/data/cookie_linebreak_v2_mod.csv")
```

Clean up our variables. 

```{r}
d$first.right <- grepl("rightB", d$first.side)
d$more.right <- grepl("rightB", d$more.side)
d$choice.right <- grepl("right", d$choice)
d$correct <- d$choice.right == d$more.right
```

Every time S clicks, it's recorded, but we only want their first click. 

```{r}
dc <- ddply(d, .(subid, trial.num), function (x) {
  y <- x[1, ]
  return(y)
  })

```

Compute RT and examine distribution. Exclude RTs > 4s. About 10% of data.

```{r}
dc$rt <- (dc$click - dc$start)/1000

qplot(rt, data=dc)

qplot(log(rt), data=dc)

mean(dc$rt > 4)
dc$rt[dc$rt > 4 | dc$rt < 0] <- NA

qplot(rt, data=dc)
```


Add ages. 

```{r}
demo <- read.csv("~/Projects/cookie_choice/data/subAges_v2.csv")
demo$age <- demo$age.mo / 12
dc <- merge(dc, demo)

qplot(age, data=demo)
```


Analysis start here
-----

Scatter plot by kids:

```{r}
ms <- ddply(dc, .(subid,age), summarize, 
            mean.correct = mean(correct, na.rm=TRUE),
            n.trials = length(correct[!is.na(correct)]))

qplot(age, mean.correct, label=subid,
      size=n.trials,
      stat="identity",
      geom=c("text"),
      position="dodge",
      data=ms) + geom_hline(yintercept=.5,lty=2) + ylim(c(0,1))

```

Median split by age, test and warmup. 

```{r}
dc$older <- dc$age > median(demo$age)
 
ms <- ddply(dc, .(older, comparison), summarize, 
            mean.correct = mean(correct, na.rm=TRUE))

qplot(comparison, mean.correct, fill=older,
      geom="bar", stat="identity",
      position="dodge",
      data=ms)

```





Now break down for warmup and test. 

```{r}
ms <- ddply(dc, .(trial.type, comparison, older), summarize, 
            mean.correct = mean(correct, na.rm=TRUE), 
            num.trials = length(correct[!is.na(correct)]))

qplot(comparison, mean.correct, fill=older,
      geom="bar", stat="identity",
      facets=.~trial.type, 
      position="dodge",
      data=ms)

print(ms)

```

Averaging across ages:


Now break down for warmup and test. 

```{r}
ms <- ddply(dc, .(trial.type, comparison), summarize, 
            mean.correct = mean(correct, na.rm=TRUE), 
            num.trials = length(correct[!is.na(correct)]))

qplot(comparison, mean.correct, 
      geom="bar", stat="identity",
      facets=.~trial.type, 
      position="dodge",
      data=ms)

print(ms)

```




Drop-out analysis.

```{r}
mss <- ddply(dc, .(subid, age, older), summarise, 
             n.trials = length(trial.num))

qplot(n.trials, facets=.~older, 
     data=mss)

```